#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Plugins.NWEA.Web.Areas.StudentSchool.Views.Detail.GoalStrandTable
{
    using System;
    
    #line 1 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
    using Cassette.Views;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
    using EdFi.Dashboards.Core.Providers.Context;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
    using EdFi.Dashboards.Presentation.Core.Models.Shared;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/StudentSchool/Views/Detail/GoalStrandTable/Get.cshtml")]
    public partial class Get : System.Web.Mvc.WebViewPage<EdFi.Dashboards.Resources.Models.CustomGrid.GridTable>
    {
        public Get()
        {
        }
        public override void Execute()
        {





WriteLiteral("\r\n");


            
            #line 7 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
  
    const string uniqueIdentifier = "GS";
    var studentUSI = EdFiDashboardContext.Current.StudentUSI.GetValueOrDefault();
    var metricVariantId = EdFiDashboardContext.Current.MetricVariantId.GetValueOrDefault();
    var edfiGridModel = new EdFiGridModel
    {
        DisplayAddRemoveColumns = false,
        DisplayInteractionMenu = true,
        FixedHeight = 10,
        GridName = "Metric" + uniqueIdentifier + metricVariantId,
        GridTable = Model,
        SizeToWindow = false,
        UniqueTableName = "Metric" + uniqueIdentifier + metricVariantId,
        DefaultSortColumn = 1,
        LegendViewNames = new List<string> { "GoalStrands" },
    };


            
            #line default
            #line hidden
WriteLiteral("\r\n<div id=\"GoalStrandTable");


            
            #line 25 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
                    Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    <script>\r\n        analyticsManager.trackDrilldown(\'GoalStrandTable\', \'");


            
            #line 27 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
                                                        Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\', \'");


            
            #line 27 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
                                                                              Write(studentUSI);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n        $(\"#Metric");


            
            #line 28 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
              Write(uniqueIdentifier+metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("-EdFiGrid-interaction-custom\").append($(\"#buttonExportAll");


            
            #line 28 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
                                                                                                          Write(uniqueIdentifier);

            
            #line default
            #line hidden
WriteLiteral("-");


            
            #line 28 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
                                                                                                                              Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\"));\r\n        $(\"#buttonExportAll");


            
            #line 29 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
                       Write(uniqueIdentifier);

            
            #line default
            #line hidden
WriteLiteral("-");


            
            #line 29 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
                                           Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\").show();\r\n    </script>\r\n    <a href=\"");


            
            #line 31 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
        Write(Url.Action("Get", "GoalStrandsExport"));

            
            #line default
            #line hidden
WriteLiteral("\" id=\"buttonExportAll");


            
            #line 31 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
                                                                     Write(uniqueIdentifier);

            
            #line default
            #line hidden
WriteLiteral("-");


            
            #line 31 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
                                                                                         Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn\" style=\"display:none;\"><i class=\"icon-floppy\"></i> EXPORT ALL</a>\r\n " +
"   <a href=\"");


            
            #line 32 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
        Write(Url.Action("Get", "GoalStrandsExport"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"hidden\">Export goal strands for metric ");


            
            #line 32 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
                                                                                                Write(metricVariantId);

            
            #line default
            #line hidden
WriteLiteral(" to csv</a>\r\n");


            
            #line 33 "..\..\Areas\StudentSchool\Views\Detail\GoalStrandTable\Get.cshtml"
      Html.RenderPartial("EdFiGrid", model: edfiGridModel);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
