#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdFi.Dashboards.Plugins.NWEA.Web.Views.Shared
{
    using System;
    
    #line 1 "..\..\Views\Shared\EdFiGridLegendGoalStrands.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Shared\EdFiGridLegendGoalStrands.cshtml"
    using EdFi.Dashboards.Presentation.Core.Models.Shared;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/EdFiGridLegendGoalStrands.cshtml")]
    public partial class EdFiGridLegendGoalStrands : System.Web.Mvc.WebViewPage<dynamic>
    {
        public EdFiGridLegendGoalStrands()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Views\Shared\EdFiGridLegendGoalStrands.cshtml"
  
    var legendItemsV4 = new List<EdFiGridLegendModel>
        {
            new EdFiGridLegendModel
                {
                    CssClass = "EdFiGrid-legend-circle EdFiGrid-legend-verygood",
                    Text = "Hi: %ile > 66",
                },
            new EdFiGridLegendModel
                {
                    CssClass = "EdFiGrid-legend-circle EdFiGrid-legend-good",
                    Text = "Avg: %ile 33 - 66",
                },
            new EdFiGridLegendModel
                {
                    CssClass = "EdFiGrid-legend-square EdFiGrid-legend-verybad",
                    Text = "Lo: %ile < 33",
                }
        };

    var legendItems2009 = new List<EdFiGridLegendModel>
    {
            new EdFiGridLegendModel
                {
                    CssClass = "EdFiGrid-legend-circle EdFiGrid-legend-verygood",
                    Text = "Hi: %ile > 80",
                },
            new EdFiGridLegendModel
                {
                    CssClass = "EdFiGrid-legend-circle EdFiGrid-legend-good",
                    Text = "HiAvg: %ile 61 - 80",
                },
            new EdFiGridLegendModel
                {
                    CssClass = "EdFiGrid-legend-rhombus EdFiGrid-legend-caution",
                    Text = "Avg: %ile 41 - 60",
                },
            new EdFiGridLegendModel
                {
                    CssClass = "EdFiGrid-legend-rhombus EdFiGrid-legend-bad",
                    Text = "LoAvg: %ile 21 - 40",
                },
            new EdFiGridLegendModel
                {
                    CssClass = "EdFiGrid-legend-square EdFiGrid-legend-verybad",
                    Text = "Lo: %ile < 21",
                }

    };



            
            #line default
            #line hidden
WriteLiteral("    <td>\r\n    WBM:\r\n    </td>\r\n");


            
            #line 57 "..\..\Views\Shared\EdFiGridLegendGoalStrands.cshtml"
 foreach (var entry in @legendItemsV4)
{


            
            #line default
            #line hidden
WriteLiteral("    <td class=\"EdFiGrid-legend-table-image\">\r\n        <div class=\"");


            
            #line 61 "..\..\Views\Shared\EdFiGridLegendGoalStrands.cshtml"
               Write(entry.CssClass);

            
            #line default
            #line hidden
WriteLiteral("\"/>\r\n    </td>\r\n");



WriteLiteral("    <td class=\"EdFiGrid-legend-table-text\">\r\n        ");


            
            #line 64 "..\..\Views\Shared\EdFiGridLegendGoalStrands.cshtml"
   Write(entry.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n    </td>\r\n");


            
            #line 66 "..\..\Views\Shared\EdFiGridLegendGoalStrands.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n</tr>\r\n<tr>\r\n    <td>\r\n        CS:\r\n    </td>\r\n");


            
            #line 73 "..\..\Views\Shared\EdFiGridLegendGoalStrands.cshtml"
     foreach (var entry in @legendItems2009)
    {


            
            #line default
            #line hidden
WriteLiteral("        <td class=\"EdFiGrid-legend-table-image\">\r\n            <div class=\"");


            
            #line 77 "..\..\Views\Shared\EdFiGridLegendGoalStrands.cshtml"
                   Write(entry.CssClass);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        </td>\r\n");



WriteLiteral("        <td class=\"EdFiGrid-legend-table-text\">\r\n            ");


            
            #line 80 "..\..\Views\Shared\EdFiGridLegendGoalStrands.cshtml"
       Write(entry.Text);

            
            #line default
            #line hidden
WriteLiteral("\r\n        </td>\r\n");


            
            #line 82 "..\..\Views\Shared\EdFiGridLegendGoalStrands.cshtml"
    }

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
